# Default values for tidb-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image: pingcap/tidb-operator
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# cluster-specific values
cluster:
  name: tidb-cluster
  enabled: false
  pd:
    size: 1
    image: pingcap/pd
  tidb:
    size: 2
    image: pingcap/tidb
  tikv:
    size: 3
    image: pingcap/tikv
