apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tidb
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: tidb-cluster
    spec:
      containers:
      - name: tidb
        image: pingcap/tidb:latest
        ports:
        - containerPort: 4000
        - containerPort: 10080
        args: ["-L=info", "--store=tikv", "--path=pd:2379?cluster=1", "-P=4000"]
        volumeMounts:
        - name: timestamp
          mountPath: /etc/localtime
      volumes:
      - name: timestamp
        hostPath:
          path: /etc/localtime

---

apiVersion: v1
kind: Service
metadata:
  name: tidb
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 4000
    targetPort: 4000
    nodePort: 30004
  - name: status
    port: 10080
    targetPort: 10080
    nodePort: 30005
  selector:
    app: tidb-cluster