apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tikv
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: tikv
    spec:
      containers:
      - name: tikv
        image: pingcap/tikv:latest
        ports:
        - containerPort: 20160
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args: ["-S", "raftkv",  "--store=/data", "--addr=0.0.0.0:20160", "--advertise-addr=$(MY_POD_IP):20160", "--pd=pd:2379", "--cluster-id=1"]
        volumeMounts:
        - name: timestamp
          mountPath: /etc/localtime
      volumes:
      - name: timestamp
        hostPath:
          path: /etc/localtime
